### PR TITLE
Removing exit that causes the quickstart to stop executing

### PR DESCRIPTION
**Pull request by jzonthemtn**
Removing exit that causes the quickstart to stop executing.

### CODE REVIEW

**Comment by epugh** [comment]
thanks.   I assumed that this returned back to the caller?    does a break need to be here versus an exit?

**Comment by jzonthemtn** [comment]
> thanks. I assumed that this returned back to the caller? does a break need to be here versus an exit?

If it hits that `exit 1`, the whole `quickstart.sh` stops. I think we want it to continue on with the indexing?

**Comment by epugh** [comment]
ah...   what do you think of the `break` ?

**Comment by jzonthemtn** [comment]
@epugh `break` worked. The `quickstart.sh` kept running:

```
............Timeout waiting for 'green' OpenSearch status reached. Proceeding on.

[QUICKSTART] Creating ecommerce index, defining its mapping & settings
```

**Pull request merged**
